#include <filesystem>

auto main() -> int
{
    namespace fs = std::filesystem;

    const fs::path out_root = fs::path{".."} / ".." / "out" / "Test-Project-1";
    const fs::path toc_file = out_root / "Project" / "TOCs" / "toc.fltoc";
    const fs::path domain_objects_dir = out_root / "Content" / "Autogenerated-Content" / "DomainObjects";

    if (!fs::exists(toc_file) || !fs::is_regular_file(toc_file))
    {
        return 1;
    }

    if (!fs::exists(domain_objects_dir) || !fs::is_directory(domain_objects_dir))
    {
        return 1;
    }

    bool has_html_file = false;
    for (const auto &entry : fs::directory_iterator(domain_objects_dir))
    {
        if (entry.is_regular_file() && entry.path().extension() == ".htm")
        {
            has_html_file = true;
            break;
        }
    }

    return has_html_file ? 0 : 1;
}
