#pragma once

#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <vector>
#include <map>
#include <cctype>
#include <algorithm>

#include "include/tinyxml2.h"

#ifdef __linux__
const std::filesystem::path g_proj_dir("../../out/Test-Project-1");
const std::filesystem::path g_toc_dir = g_proj_dir / "Project/TOCs";
#else
const std::filesystem::path g_proj_dir("..\\..\\out\\Test-Project-1");
const std::filesystem::path g_toc_dir = g_proj_dir / "Project\\TOCs";
#endif

const std::filesystem::path g_content_dir = g_proj_dir / "Content";
const std::filesystem::path g_autogen_dir = g_content_dir / "Autogenerated-Content";
const std::filesystem::path g_do_dir = g_autogen_dir / "DomainObjects";
const std::filesystem::path g_cons_dir = g_autogen_dir / "Constructors";
const std::filesystem::path g_props_dir = g_autogen_dir / "Properties";
const std::filesystem::path g_meths_dir = g_autogen_dir / "Methods";
const std::filesystem::path g_funcs_dir = g_autogen_dir / "Functions";

const std::string g_placeholder = "%%PLACEHOLDER%%";
const std::string g_header_color = "#808080";

enum class TopicType
{
    domain_object,
    function,
    property,
    method,
    constructor,
    available_dos,
    available_funcs
};

struct TypeInfo
{
    std::filesystem::path dir;
    std::string suffix;
};

static const std::map<TopicType, TypeInfo> g_type_map = {
    {TopicType::domain_object, {g_do_dir, " Object"}},
    {TopicType::constructor, {g_cons_dir, " Constructor"}},
    {TopicType::property, {g_props_dir, " Property"}},
    {TopicType::method, {g_meths_dir, " Method"}},
    {TopicType::function, {g_funcs_dir, " Function"}},
    {TopicType::available_dos, {g_do_dir, ""}},
    {TopicType::available_funcs, {g_funcs_dir, ""}}};

struct CaseInsensitiveComparer
{
    bool operator()(const std::string &a, const std::string &b) const
    {
        return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end(), [](char c1, char c2)
                                            { return std::tolower(static_cast<unsigned char>(c1)) < std::tolower(static_cast<unsigned char>(c2)); });
    }
};

struct DomainObject
{
    std::string Name;
    std::vector<std::string> Constructors;
    std::vector<std::string> Properties;
    std::map<std::string, std::vector<std::string>, CaseInsensitiveComparer> Methods;
};

const std::string g_bad_chars = "(),<>{}";
const std::string g_good_chars = "__-____";

inline auto sanitize_filename = [](std::string &filename, const std::string &chars, const std::string &replacements) -> void
{
    for (size_t i = 0; i < chars.size(); ++i)
    {
        std::replace(filename.begin(), filename.end(), chars[i], replacements[i]);
    }
};