#pragma once

#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <vector>
#include <map>
#include <cctype>
#include <algorithm>
#include <string>
#include <string_view>

#include "include/tinyxml2.h"

inline const std::filesystem::path g_proj_dir{"../../out/Test-Project-1"};
inline const std::filesystem::path g_toc_dir = g_proj_dir / "Project" / "TOCs";

inline const std::filesystem::path g_content_dir = g_proj_dir / "Content";
inline const std::filesystem::path g_autogen_dir = g_content_dir / "Autogenerated-Content";
inline const std::filesystem::path g_do_dir = g_autogen_dir / "DomainObjects";
inline const std::filesystem::path g_cons_dir = g_autogen_dir / "Constructors";
inline const std::filesystem::path g_props_dir = g_autogen_dir / "Properties";
inline const std::filesystem::path g_meths_dir = g_autogen_dir / "Methods";
inline const std::filesystem::path g_funcs_dir = g_autogen_dir / "Functions";

inline const std::string g_placeholder = "%%PLACEHOLDER%%";
inline const std::string g_header_color = "#808080";

enum class TopicType
{
    domain_object,
    function,
    property,
    method,
    constructor,
    available_dos,
    available_funcs
};

struct TypeInfo
{
    std::filesystem::path dir;
    std::string suffix;
};

inline const std::map<TopicType, TypeInfo> g_type_map = {
    {TopicType::domain_object, {g_do_dir, " Object"}},
    {TopicType::constructor, {g_cons_dir, " Constructor"}},
    {TopicType::property, {g_props_dir, " Property"}},
    {TopicType::method, {g_meths_dir, " Method"}},
    {TopicType::function, {g_funcs_dir, " Function"}},
    {TopicType::available_dos, {g_do_dir, ""}},
    {TopicType::available_funcs, {g_funcs_dir, ""}}};

struct CaseInsensitiveComparer
{
    bool operator()(const std::string &a, const std::string &b) const noexcept
    {
        return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end(), [](char c1, char c2)
                                            { return std::tolower(static_cast<unsigned char>(c1)) < std::tolower(static_cast<unsigned char>(c2)); });
    }
};

struct DomainObject
{
    std::string Name;
    std::vector<std::string> Constructors;
    std::vector<std::string> Properties;
    std::map<std::string, std::vector<std::string>, CaseInsensitiveComparer> Methods;
};

inline constexpr std::string_view g_bad_chars = "(),<>{}";
inline constexpr std::string_view g_good_chars = "__-____";

inline void sanitize_filename(std::string &filename, std::string_view chars, std::string_view replacements)
{
    if (chars.size() != replacements.size())
    {
        return;
    }

    for (size_t i = 0; i < chars.size(); ++i)
    {
        std::replace(filename.begin(), filename.end(), chars[i], replacements[i]);
    }
}