#pragma once

#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <vector>
#include <unordered_map>

#include "include/tinyxml2.h"

#ifdef __linux__
const std::filesystem::path g_proj_dir("../../out/Test-Project-1");
const std::filesystem::path g_toc_dir = g_proj_dir / "Project/TOCs";
#else
const std::filesystem::path g_proj_dir("..\\..\\out\\Test-Project-1");
const std::filesystem::path g_toc_dir = g_proj_dir / "Project\\TOCs";
#endif

const std::filesystem::path g_content_dir = g_proj_dir / "Content";
const std::filesystem::path g_autogen_dir = g_content_dir / "Autogenerated-Content";
const std::filesystem::path g_do_dir = g_autogen_dir / "DomainObjects";
const std::filesystem::path g_cons_dir = g_autogen_dir / "Constructors";
const std::filesystem::path g_props_dir = g_autogen_dir / "Properties";
const std::filesystem::path g_meths_dir = g_autogen_dir / "Methods";
const std::filesystem::path g_funcs_dir = g_autogen_dir / "Functions";

const std::string g_placeholder = "%%PLACEHOLDER%%";
const std::string g_header_color = "#808080";

struct DomainObject
{
    std::string Name;
    std::vector<std::string> Constructors;
    std::vector<std::string> Properties;
    std::unordered_map<std::string, std::vector<std::string>> Methods;
};